apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex
  annotations:
    # kubernetes.io/tls-acme: "true"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  # tls:
  # - hosts:
  #   - dex.gangwaydexdemo.com
  #   secretName: dex-tls
  rules:
  - host: dex.gangwaydexdemo.com
    http:
      paths:
      - backend:
          serviceName: dex
          servicePort: https
