apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gangway
  namespace: gangway
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  template:
    metadata:
      labels:
        app: gangway
        revision: "1"
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v2.0.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway-key
                  key: sesssionkey
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: tls-dir
              mountPath: /etc/dex/pki
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gangway
          configMap:
            name: gangway
        - name: tls-dir
          hostPath:
            path: /etc/dex/pki
            type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: gangway
data:
  gangway.yaml: |
    # The address to listen on. Defaults to 0.0.0.0 to listen on all interfaces.
    # Env var: GANGWAY_HOST
    # host: 0.0.0.0

    # The port to listen on. Defaults to 8080.
    # Env var: GANGWAY_PORT
    # port: 8080

    # Should Gangway serve TLS vs. plain HTTP? Default: false
    # Env var: GANGWAY_SERVE_TLS
    # serveTLS: false
    serveTLS: true

    # The public cert file (including root and intermediates) to use when serving
    # TLS.
    # Env var: GANGWAY_CERT_FILE
    # certFile: /etc/gangway/tls/tls.crt
    certFile: /etc/dex/pki/dex.crt

    # The private key file when serving TLS.
    # Env var: GANGWAY_KEY_FILE
    # keyFile: /etc/gangway/tls/tls.key
    keyFile: /etc/dex/pki/dex.key

    # The cluster name. Used in UI and kubectl config instructions.
    # Env var: GANGWAY_CLUSTER_NAME
    # clusterName: "${CLUSTER_NAME}"
    clusterName: "dorf_cluster"

    # OAuth2 URL to start authorization flow.
    # Env var: GANGWAY_AUTHORIZE_URL
    authorizeURL: "https://dex.gangwaydexdemo.com:32000/dex/auth"

    # OAuth2 URL to obtain access tokens.
    # Env var: GANGWAY_TOKEN_URL
    # tokenURL: "https://dex.gangwaydexdemo.com/dex/token"
    # tokenURL: "https://dex.default.svc.cluster.local:5556/dex/token"
    tokenURL: "https://dex.gangwaydexdemo.com:5556/dex/token"

    # Endpoint that provides user profile information [optional]. Not all providers
    # will require this.
    # Env var: GANGWAY_AUDIENCE
    # audience: "https://oauth.example.com/userinfo"

    # Used to specify the scope of the requested Oauth authorization.
    # scopes: ["openid", "profile", "email", "offline_access"]

    # Where to redirect back to. This should be a URL where gangway is reachable.
    # Typically this also needs to be registered as part of the oauth application
    # with the oAuth provider.
    # Env var: GANGWAY_REDIRECT_URL
    # redirectURL: "http://gangwaydexdemo.com:9555/callback"
    redirectURL: "https://gangway.gangwaydexdemo.com:32001/callback"

    # API client ID as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_ID
    clientID: "gangway"

    # API client secret as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_SECRET
    clientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0"

    # The JWT claim to use as the username. This is used in UI.
    # Default is "nickname".
    # Env var: GANGWAY_USERNAME_CLAIM
    usernameClaim: "sub"

    # The JWT claim to use as the email claim. This is used to name the
    # "user" part of the config. Default is "email".
    # Env var: GANGWAY_EMAIL_CLAIM
    emailClaim: "email"

    # The API server endpoint used to configure kubectl
    # Env var: GANGWAY_APISERVER_URL
    apiServerURL: "https://k8sapi.gangwaydexdemo.com:6443"
    # apiServerURL: "https://kubernetes.default.svc.cluster.local:6443"

    # The path to find the CA bundle for the API server. Used to configure kubectl.
    # This is typically mounted into the default location for workloads running on
    # a Kubernetes cluster and doesn't need to be set.
    # Env var: GANGWAY_CLUSTER_CA_PATH
    # cluster_ca_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    # The path to a root CA to trust for self signed certificates at the Oauth2 URLs
    # Env var: GANGWAY_TRUSTED_CA_PATH
    trustedCAPath: /etc/dex/pki/dex-ca.crt
---
kind: Service
apiVersion: v1
metadata:
  name: gangwaysvc
  namespace: gangway
  labels:
    app: gangway
spec:
  type: NodePort
  ports:
  - name: gangway
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: gangway
